export const CommonConstant = {
  USER_NAME_MAX_LENGTH: 10,
  USER_NAME_PREFIX_MAX_LENGTH: 25,
  GROUP_NAME_MAX_LENGTH: 50,
  GROUP_DESCRIPTION_MAX_LENGTH: 100,
  CALENDAR_EVENT_TITLE_MAX_LENGTH: 50,
  CALENDAR_EVENT_DESCRIPTION_MAX_LENGTH: 100,
  CALENDAR_EVENT_LOCATION_MAX_LENGTH: 100,
};
