name: build&deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: moyeo/moyeo-backend:${{ github.sha }}
          platforms: |
            linux/amd64

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            rm -rf .env.production
            echo "PORT=3000" >> .env.production

            docker stop moyeo-backend || true
            docker rm moyeo-backend || true
            docker pull moyeo/moyeo-backend:${{ github.sha }}
            docker run -d --name moyeo-backend -p ${{ secrets.OUT_PORT }}:3000 --env-file .env.production moyeo/moyeo-backend:${{ github.sha }}
